const std = @import("std");

pub const data = std.StaticStringMap([]const u8).initComptime(.{
  .{ "data_path", "./zig-out/share/unemployed-zig/" },
});

pub const IMF_INDICATORS = std.StaticStringMap([]const u8).initComptime(.{
  .{ "BCA", "Current account balance (U.S. dollars)" },
  .{ "BCA_NGDPD", "Current account balance (Percent of GDP)" },
  .{ "FLIBOR6", "Six-month London interbank offered rate (LIBOR) (Percent)" },
  .{ "GGR", "General government revenue (National currency)" },
  .{ "GGR_NGDP", "General government revenue (Percent of GDP)" },
  .{ "GGSB", "General government structural balance (National currency)" },
  .{ "GGSB_NPGDP", "General government structural balance (Percent of potential GDP)" },
  .{ "GGX", "General government total expenditure (National currency)" },
  .{ "GGXCNL", "General government net lending/borrowing (National currency)" },
  .{ "GGXCNL_NGDP", "General government net lending/borrowing (Percent of GDP)" },
  .{ "GGXONLB", "General government primary net lending/borrowing (National currency)" },
  .{ "GGXONLB_NGDP", "General government primary net lending/borrowing (Percent of GDP)" },
  .{ "GGXWDG", "General government gross debt (National currency)" },
  .{ "GGXWDG_NGDP", "General government gross debt (Percent of GDP)" },
  .{ "GGXWDN", "General government net debt (National currency)" },
  .{ "GGXWDN_NGDP", "General government net debt (Percent of GDP)" },
  .{ "GGX_NGDP", "General government total expenditure (Percent of GDP)" },
  .{ "LE", "Employment (Persons)" },
  .{ "LP", "Population (Persons)" },
  .{ "LUR", "Unemployment rate (Percent of total labor force)" },
  .{ "NGAP_NPGDP", "Output gap in percent of potential GDP (Percent of potential GDP)" },
  .{ "NGDP", "Gross domestic product, current prices (National currency)" },
  .{ "NGDPD", "Gross domestic product, current prices (U.S. dollars)" },
  .{ "NGDPDPC", "Gross domestic product per capita, current prices (U.S. dollars)" },
  .{ "NGDPPC", "Gross domestic product per capita, current prices (National currency)" },
  .{ "NGDPRPC", "Gross domestic product per capita, constant prices (National currency)" },
  .{ "NGDP_D", "Gross domestic product, deflator (Index)" },
  .{ "NGDP_FY", "Gross domestic product corresponding to fiscal year, current prices (National currency)" },
  .{ "NGDP_R", "Gross domestic product, constant prices (National currency)" },
  .{ "NGDP_RPCH", "Gross domestic product, constant prices (Percent change)" },
  .{ "NGSD_NGDP", "Gross national savings (Percent of GDP)" },
  .{ "NID_NGDP", "Total investment (Percent of GDP)" },
  .{ "PCPI", "Inflation, average consumer prices (Index)" },
  .{ "PCPIE", "Inflation, end of period consumer prices (Index)" },
  .{ "PCPIEPCH", "Inflation, end of period consumer prices (Percent change)" },
  .{ "PCPIPCH", "Inflation, average consumer prices (Percent change)" },
  .{ "PPPEX", "Implied PPP conversion rate (National currency per current international dollar)" },
  .{ "PPPGDP", "Gross domestic product based on purchasing-power-parity (PPP) valuation of country GDP (Current international dollar)" },
  .{ "PPPPC", "Gross domestic product based on purchasing-power-parity (PPP) per capita GDP (Current international dollar)" },
  .{ "PPPSH", "Gross domestic product based on purchasing-power-parity (PPP) share of world total (Percent)" },
  .{ "TMG_RPCH", "Volume of Imports of goods (Percent change)" },
  .{ "TM_RPCH", "Volume of imports of goods and services (Percent change)" },
  .{ "TXG_RPCH", "Volume of exports of goods (Percent change)" },
  .{ "TX_RPCH", "Volume of exports of goods and services (Percent change)" },
});
